<a href="https://colab.research.google.com/github/Mobashera-Alam/CS-5783-MachineLearning/blob/main/Assignment3/P3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Dimension of input is 6*6*1 and dimension of Kernel is 3X3X1. 
No of parameters in the kernel = 3X3X1+1 = 10
2. Output activation map = (W1-F+2P)/S +1 = 4X4X1 (no padding,P =0, S=1,W1=6,F=3)

3. Output after maxpooling = (W1-F)/S +1= 2X2X1    (W1=4,F=3,S=1)


In [70]:
#2

from datetime import datetime
from packaging import version

import tensorflow as tf
from tensorflow import keras

import tensorboard
import matplotlib.pyplot as plt

import numpy as np

In [89]:
#Problem 2
#input
x =[[7,5,0,0,3,2],[6,4,5,1,4,8],[9,0,2,2,5,4],[6,3,4,7,9,8],[5,7,5,6,9,0],[7,9,0,8,2,3]]
x = np.array(x)
print(x.shape)

#Kernel
f = [[1,0,-1],[2,0,-2],[1,0,-1]]
f = np.array(f)
print(f.shape)


k=0
o = np.zeros((4,4))

for l in range(4):
  for m in range(4):
    k=0
    for i in range (3):
      for j in range(3):
        sum = np.dot(x[l+i][m+j],f[i][j])
        k = k+sum
        o[l,m]=k

k=0
print('Output activation map:',o)

# Problem 3: Apply maxpool with the same filter dimension 3X3
o1 = np.zeros((2,2))   #output of next layer
for l in range(2):
  for m in range(2):
    k = np.max(o[l:l+3,m:m+3])        
    o1[l,m]=k

print('Output after maxpool operation:',o1)

(6, 6)
(3, 3)
Output activation map: [[ 16.   9.  -4. -18.]
 [ 17.  -5. -10. -12.]
 [ 11.  -9. -17.   2.]
 [  9.  -1. -15.  16.]]
Output after maxpool operation: [[17.  9.]
 [17. 16.]]
